defaultSemverRangePrefix: ""

packageExtensions:
  istanbul-lib-processinfo@*:
    dependencies:
      mkdirp: "*"
  tcompare@*:
    dependencies:
      diff: "*"

yarnPath: .yarn/releases/yarn-sources.cjs
