yarnPath: .yarn/releases/yarn-2.3.3.cjs
defaultSemverRangePrefix: ""
packageExtensions:
  "istanbul-lib-processinfo@*":
    dependencies:
      mkdirp: "*"
  "tcompare@*":
    dependencies:
      diff: "*"